version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-estoque
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mercadinho_estoque
      SPRING_DATASOURCE_USERNAME: iuri
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: estoque-mercado-db
    environment:
      MYSQL_DATABASE: mercadinho_estoque
      MYSQL_USER: iuri
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
